#!/bin/sh

# This script is here to allow testing this source
# directory build of mwnci.
#
# I.e it can take a mwnci script or run the repl using
# only the source directory includes/executables to seeif it's
# all working as it should be before an install.
#
# Just saves me time typing

DIR=`dirname $0`
[ $# -gt 1 ] && shift
export INCLUDEPATH=${DIR}/includes

${DIR}/mwnci $@
