dummy:

install:
	mkdir -p ${HOME}/.vim/ftdetect
	mkdir -p ${HOME}/.vim/syntax
	cp ftdetect/mwnci.vim ${HOME}/.vim/ftdetect
	cp syntax/mwnci.vim ${HOME}/.vim/syntax
	cat filetype.vim >> ${HOME}/.vim/filetype.vim
